spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mainProjectStack?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mainProjectUser
    password: 12345678
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:project;NON_KEYWORDS=USER
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: true
  profiles:
    include: database
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
