spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:

    url: jdbc:h2:mem:catdog;NON_KEYWORDS=LIKE,ORDER,ITEM;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
      ddl-auto: create
      auto_quote_keyword: true
    show_sql: true

mail:
  address:
    admin: admin@gmail.com
jwt:
  key:
    secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 1000000
  refresh-token-expiration-minutes: 420
