spring:
  jpa:
    properties:
      hibernate:
      ddl-auto: create
      auto_quote_keyword: true
    show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: sanguk821@gmail.com
    password: pxroizhqydkvcctp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cloud:
  aws:
    s3:
      bucket:

mail:
  address:
    admin: admin@gmail.com
jwt:
  key:
    secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 1000000
  refresh-token-expiration-minutes: 420
