spring:
  jpa:
    properties:
      hibernate:
      ddl-auto: create
      auto_quote_keyword: true
    show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: sanguk821@gmail.com
    password: ${SMTP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_OAUTH_CLIENT_ID}
            clientSecret: ${GOOGLE_OAUTH_SECRET}
            redirect-uri: ${GOOGLE_OAUTH_REDIRECT}
            scope:
              - email
              - profile
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#
#      enable-auto-commit: true
#      max-poll-records: 1000
#
#
#      group-id: oingdaddy
#
#      auto-offset-reset: latest
#
#    template:
#      default-topic: oingdaddy
mail:
  address:
    admin: admin@gmail.com
jwt:
  key:
    secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 1000000
  refresh-token-expiration-minutes: 420
cloud:
  aws:
    credentials:
      accessKey: ${s3_access_key}
      secretKey: ${s3_secret_key}
    s3:
      bucket: catdogbucket
      folder:
    region:
      static: ap-northeast-2
    stack:
      auto: false

