spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:project
  sql:
    init:
      schema-locations:
      data-locations:
    jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      format_sql: true
  mvc:
    converters:
      preferred-json-mapper: =gson
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
mail:
  address:
    admin: admin@gmail.com
jwt:
  key:
    secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 420