drop table if exists articles CASCADE
drop table if exists comment CASCADE
drop table if exists comment_like CASCADE
drop table if exists comment_report CASCADE
drop table if exists follow CASCADE
drop table if exists give_take CASCADE
drop table if exists items CASCADE
drop table if exists likes CASCADE
drop table if exists order_item CASCADE
drop table if exists orders CASCADE
drop table if exists report CASCADE
drop table if exists tag CASCADE
drop table if exists user_roles CASCADE
drop table if exists users CASCADE
drop table if exists wallet CASCADE
create table articles (article_id bigint generated by default as identity, created_at timestamp, updated_at timestamp, article_img varchar(255) not null, article_status varchar(255), content varchar(200), like_cnt integer not null, report_cnt integer not null, views integer not null, yummy_cnt integer not null, user_id bigint, primary key (article_id))
create table comment (comment_id bigint generated by default as identity, created_at timestamp, updated_at timestamp, comment_status varchar(255), content varchar(200) not null, like_cnt integer not null, report_cnt integer not null, article_id bigint, user_id bigint, primary key (comment_id))
create table comment_like (comment_like_id bigint generated by default as identity, comment_id bigint, user_id bigint, primary key (comment_like_id))
create table comment_report (comment_report_id bigint generated by default as identity, content varchar(255) not null, comment_id bigint, user_id bigint, primary key (comment_report_id))
create table follow (follow_id bigint generated by default as identity, created_at timestamp, updated_at timestamp, followed_user_id bigint, following_user_id bigint, primary key (follow_id))
create table give_take (give_take_id bigint generated by default as identity, created_at timestamp, updated_at timestamp, give_yummy integer not null, article_id bigint, give_wlt_id bigint, take_wlt_id bigint, primary key (give_take_id))
create table items (item_id bigint generated by default as identity, created_at timestamp, updated_at timestamp, item_img varchar(255), item_name varchar(255) not null, price integer not null, stock integer not null, primary key (item_id))
create table likes (like_id integer generated by default as identity, article_id bigint, user_id bigint, primary key (like_id))
create table order_item (order_item_id bigint generated by default as identity, created_at timestamp, updated_at timestamp, order_price integer not null, quantity integer not null, item_id bigint, order_id bigint, primary key (order_item_id))
create table orders (order_id bigint generated by default as identity, created_at timestamp, updated_at timestamp, wallet_id bigint, primary key (order_id))
create table report (report_id integer generated by default as identity, content varchar(255) not null, article_id bigint, user_id bigint, primary key (report_id))
create table tag (tag_id bigint generated by default as identity, created_at timestamp, updated_at timestamp, tag_name varchar(255) not null, primary key (tag_id))
create table user_roles (user_user_id bigint not null, roles varchar(255))
create table users (user_id bigint generated by default as identity, created_at timestamp, updated_at timestamp, content varchar(200), email varchar(50) not null, password varchar(255) not null, user_birth date, user_gender varchar(255), user_img varchar(255), user_name varchar(100) not null, user_status integer, user_type varchar(255), primary key (user_id))
create table wallet (wallet_id bigint generated by default as identity, created_at timestamp, updated_at timestamp, yummy integer not null, user_id bigint, primary key (wallet_id))
alter table tag add constraint UK_1r1tyf6uga9k6jwdqnoqwtk2a unique (tag_name)
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table articles add constraint FKlc3sm3utetrj1sx4v9ahwopnr foreign key (user_id) references users
alter table comment add constraint FK8049ejo8mr24lp42nvur9feyj foreign key (article_id) references articles
alter table comment add constraint FKqm52p1v3o13hy268he0wcngr5 foreign key (user_id) references users
alter table comment_like add constraint FKqlv8phl1ibeh0efv4dbn3720p foreign key (comment_id) references comment
alter table comment_like add constraint FKl5wrmp8eoy5uegdo3473jqqi foreign key (user_id) references users
alter table comment_report add constraint FK8ugevhla12t9n0uw4o0rkvnth foreign key (comment_id) references comment
alter table comment_report add constraint FKr59oxeybgry0ocb3twdab97ik foreign key (user_id) references users
alter table follow add constraint FKelnr125h8iqx27118xlg57e0b foreign key (followed_user_id) references users
alter table follow add constraint FKatlkvsyd2ipaq17txxs3wptw0 foreign key (following_user_id) references users
alter table give_take add constraint FKrm880kiaqmqjjtx4okfd41xqd foreign key (article_id) references articles
alter table give_take add constraint FKnd0tswi81s6gbqgcxpxxfxjvh foreign key (give_wlt_id) references wallet
alter table give_take add constraint FKh3s8ejduvnpk3w2wh78sv872u foreign key (take_wlt_id) references wallet
alter table likes add constraint FKic6sfk54mitq78b48367cfiet foreign key (article_id) references articles
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users
alter table order_item add constraint FKo5d8io03ue2y89j3wbnju0let foreign key (item_id) references items
alter table order_item add constraint FKt4dc2r9nbvbujrljv3e23iibt foreign key (order_id) references orders
alter table orders add constraint FK8af1p36hch7wt2bbqe3o0gqf1 foreign key (wallet_id) references wallet
alter table report add constraint FKi451cgaw69k9j91re986rripx foreign key (article_id) references articles
alter table report add constraint FKq50wsn94sc3mi90gtidk0k34a foreign key (user_id) references users
alter table user_roles add constraint FK5gikiw021w6y16a8t5vjwqwyj foreign key (user_user_id) references users
alter table wallet add constraint FKgbusavqq0bdaodex4ee6v0811 foreign key (user_id) references users
